export type TClusterIconGlyph =
    | 'server'
    | 'cloud'
    | 'database'
    | 'flask'
    | 'shield'
    | 'box'
    | 'globe'
    | 'cpu'
    | 'rocket'
    | 'flame'
    | 'bug'
    | 'lock'
    | 'building'
    | 'house'
    | 'wrench'
    | 'zap'
