/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBreadcrumbs: typeof import('./src/components/app/breadcrumbs/AppBreadcrumbs.vue')['default']
    AppIcon: typeof import('./src/components/app/AppIcon.vue')['default']
    AppLoading: typeof import('./src/components/app/AppLoading.vue')['default']
    AppLogo: typeof import('./src/components/app/AppLogo.vue')['default']
    AppModals: typeof import('./src/components/app/AppModals.vue')['default']
    AppThemeSwitcher: typeof import('./src/components/app/AppThemeSwitcher.vue')['default']
    AppToast: typeof import('./src/components/app/AppToast.vue')['default']
    AsyncBreadcrumbItem: typeof import('./src/components/app/breadcrumbs/AsyncBreadcrumbItem.vue')['default']
    ConfirmDialog: typeof import('./src/components/common/ConfirmDialog.vue')['default']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    RecordSelect: typeof import('./src/components/common/select/RecordSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterProgressBar: typeof import('./src/components/app/RouterProgressBar.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    UiFormField: typeof import('./src/components/common/form/UiFormField.vue')['default']
    UiModal: typeof import('./src/components/common/modal/UiModal.vue')['default']
    UiPagination: typeof import('./src/components/common/pagination/UiPagination.vue')['default']
    UiSection: typeof import('./src/components/common/section/UiSection.vue')['default']
    UiSelect: typeof import('./src/components/common/select/UiSelect.vue')['default']
    UiSkeletons: typeof import('./src/components/common/UiSkeletons.vue')['default']
    UiTabBar: typeof import('./src/components/common/tabBar/UiTabBar.vue')['default']
    UiToggle: typeof import('./src/components/common/toggle/UiToggle.vue')['default']
  }
}
