// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Cancel(id: string): $CancellablePromise<$models.DownloadResult> {
    return $Call.ByID(1561197273, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Start(spec: $models.DownloadSpec): $CancellablePromise<$models.StartResult> {
    return $Call.ByID(1833463061, spec).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DownloadResult.createFrom;
const $$createType1 = $models.StartResult.createFrom;
