// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DownloadResult {
    "success": boolean;
    "error": string;

    /** Creates a new DownloadResult instance. */
    constructor($$source: Partial<DownloadResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadResult($$parsedSource as Partial<DownloadResult>);
    }
}

export class DownloadSpec {
    "url": string;
    "path": string;
    "headers": { [_ in string]?: string };

    /** Creates a new DownloadSpec instance. */
    constructor($$source: Partial<DownloadSpec> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("headers" in $$source)) {
            this["headers"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadSpec instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadSpec {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField2_0($$parsedSource["headers"]);
        }
        return new DownloadSpec($$parsedSource as Partial<DownloadSpec>);
    }
}

export class StartResult {
    "success": boolean;
    "downloadId": string;
    "error": string;

    /** Creates a new StartResult instance. */
    constructor($$source: Partial<StartResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("downloadId" in $$source)) {
            this["downloadId"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartResult instance from a string or object.
     */
    static createFrom($$source: any = {}): StartResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartResult($$parsedSource as Partial<StartResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
