// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class LaunchSpec {
    "path": string;
    "args": string[];
    "dir": string;

    /** Creates a new LaunchSpec instance. */
    constructor($$source: Partial<LaunchSpec> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = [];
        }
        if (!("dir" in $$source)) {
            this["dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LaunchSpec instance from a string or object.
     */
    static createFrom($$source: any = {}): LaunchSpec {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField1_0($$parsedSource["args"]);
        }
        return new LaunchSpec($$parsedSource as Partial<LaunchSpec>);
    }
}

export class ProcessInfo {
    "id": string;
    "command": string;
    "pty": boolean;
    "startedAt": string;
    "running": boolean;

    /** Creates a new ProcessInfo instance. */
    constructor($$source: Partial<ProcessInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("pty" in $$source)) {
            this["pty"] = false;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "";
        }
        if (!("running" in $$source)) {
            this["running"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ProcessInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcessInfo($$parsedSource as Partial<ProcessInfo>);
    }
}

export class ProcessListResult {
    "success": boolean;
    "processes": ProcessInfo[];
    "error": string;

    /** Creates a new ProcessListResult instance. */
    constructor($$source: Partial<ProcessListResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("processes" in $$source)) {
            this["processes"] = [];
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessListResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ProcessListResult {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("processes" in $$parsedSource) {
            $$parsedSource["processes"] = $$createField1_0($$parsedSource["processes"]);
        }
        return new ProcessListResult($$parsedSource as Partial<ProcessListResult>);
    }
}

export class ProcessResult {
    "success": boolean;
    "error": string;

    /** Creates a new ProcessResult instance. */
    constructor($$source: Partial<ProcessResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ProcessResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcessResult($$parsedSource as Partial<ProcessResult>);
    }
}

export class StartResult {
    "success": boolean;
    "processId": string;
    "error": string;

    /** Creates a new StartResult instance. */
    constructor($$source: Partial<StartResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("processId" in $$source)) {
            this["processId"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartResult instance from a string or object.
     */
    static createFrom($$source: any = {}): StartResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartResult($$parsedSource as Partial<StartResult>);
    }
}

export class StartSpec {
    "command": string;
    "args": string[];

    /**
     * An empty value removes the variable instead of setting it to "".
     */
    "env": { [_ in string]?: string };
    "dir": string;
    "pty": boolean;
    "cols": number;
    "rows": number;

    /** Creates a new StartSpec instance. */
    constructor($$source: Partial<StartSpec> = {}) {
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = [];
        }
        if (!("env" in $$source)) {
            this["env"] = {};
        }
        if (!("dir" in $$source)) {
            this["dir"] = "";
        }
        if (!("pty" in $$source)) {
            this["pty"] = false;
        }
        if (!("cols" in $$source)) {
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartSpec instance from a string or object.
     */
    static createFrom($$source: any = {}): StartSpec {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField1_0($$parsedSource["args"]);
        }
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField2_0($$parsedSource["env"]);
        }
        return new StartSpec($$parsedSource as Partial<StartSpec>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ProcessInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
