// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CloseAll(): $CancellablePromise<void> {
    return $Call.ByID(2633473112);
}

export function Kill(id: string): $CancellablePromise<$models.ProcessResult> {
    return $Call.ByID(448801307, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function List(): $CancellablePromise<$models.ProcessListResult> {
    return $Call.ByID(1095699363).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Resize(id: string, cols: number, rows: number): $CancellablePromise<$models.ProcessResult> {
    return $Call.ByID(3324596243, id, cols, rows).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Start(spec: $models.StartSpec): $CancellablePromise<$models.StartResult> {
    return $Call.ByID(2401476761, spec).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Write(id: string, data: string): $CancellablePromise<$models.ProcessResult> {
    return $Call.ByID(2964084302, id, data).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ProcessResult.createFrom;
const $$createType1 = $models.ProcessListResult.createFrom;
const $$createType2 = $models.StartResult.createFrom;
