// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Expand(path: string): $CancellablePromise<$models.EnvResult> {
    return $Call.ByID(304425835, path).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Get(name: string): $CancellablePromise<$models.EnvResult> {
    return $Call.ByID(1378152461, name).then(($result: any) => {
        return $$createType0($result);
    });
}

export function PathSeparator(): $CancellablePromise<$models.EnvResult> {
    return $Call.ByID(3530662203).then(($result: any) => {
        return $$createType0($result);
    });
}

export function UserHomeDir(): $CancellablePromise<$models.EnvResult> {
    return $Call.ByID(348505878).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.EnvResult.createFrom;
