// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AbsolutePath(path: string): $CancellablePromise<$models.IOResult> {
    return $Call.ByID(3849291605, path).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CopyFile(src: string, dst: string): $CancellablePromise<$models.IOResult> {
    return $Call.ByID(3090084796, src, dst).then(($result: any) => {
        return $$createType0($result);
    });
}

export function FileExists(path: string): $CancellablePromise<$models.IOResult> {
    return $Call.ByID(1943279333, path).then(($result: any) => {
        return $$createType0($result);
    });
}

export function MakeDir(path: string): $CancellablePromise<$models.IOResult> {
    return $Call.ByID(3307724720, path).then(($result: any) => {
        return $$createType0($result);
    });
}

export function MoveFile(source: string, target: string): $CancellablePromise<$models.IOResult> {
    return $Call.ByID(387668444, source, target).then(($result: any) => {
        return $$createType0($result);
    });
}

export function OpenDir(path: string): $CancellablePromise<$models.IOResult> {
    return $Call.ByID(144253182, path).then(($result: any) => {
        return $$createType0($result);
    });
}

export function OpenURI(uri: string): $CancellablePromise<$models.IOResult> {
    return $Call.ByID(2612678199, uri).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ReadDir(path: string): $CancellablePromise<$models.IOResult> {
    return $Call.ByID(3230217446, path).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ReadFile(path: string, options: $models.IOOptions): $CancellablePromise<$models.IOResult> {
    return $Call.ByID(774159449, path, options).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RemoveFile(path: string): $CancellablePromise<$models.IOResult> {
    return $Call.ByID(3500417105, path).then(($result: any) => {
        return $$createType0($result);
    });
}

export function UnzipGZFile(path: string, output: string): $CancellablePromise<$models.IOResult> {
    return $Call.ByID(2519522780, path, output).then(($result: any) => {
        return $$createType0($result);
    });
}

export function UnzipTarGZFile(path: string, output: string): $CancellablePromise<$models.IOResult> {
    return $Call.ByID(3029009137, path, output).then(($result: any) => {
        return $$createType0($result);
    });
}

export function UnzipZIPFile(path: string, output: string): $CancellablePromise<$models.IOResult> {
    return $Call.ByID(2068705196, path, output).then(($result: any) => {
        return $$createType0($result);
    });
}

export function WriteFile(path: string, content: string, options: $models.IOOptions): $CancellablePromise<$models.IOResult> {
    return $Call.ByID(2515023744, path, content, options).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.IOResult.createFrom;
