// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class IOOptions {
    "Mode": string;
    "Range": string;

    /** Creates a new IOOptions instance. */
    constructor($$source: Partial<IOOptions> = {}) {
        if (!("Mode" in $$source)) {
            this["Mode"] = "";
        }
        if (!("Range" in $$source)) {
            this["Range"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IOOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): IOOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IOOptions($$parsedSource as Partial<IOOptions>);
    }
}

export class IOResult {
    "success": boolean;
    "data": string;

    /** Creates a new IOResult instance. */
    constructor($$source: Partial<IOResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IOResult instance from a string or object.
     */
    static createFrom($$source: any = {}): IOResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IOResult($$parsedSource as Partial<IOResult>);
    }
}
