export type TKubeFailureKind =
    | 'unauthorized'
    | 'forbidden'
    | 'missing'
    | 'conflict'
    | 'invalid'
    | 'expired'
    | 'throttled'
    | 'unavailable'
    | 'serverError'
    | 'timeout'
    | 'tls'
    | 'unreachable'
    | 'disconnected'
    | 'unknown'
