// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ChannelActionResult {
    "success": boolean;
    "error": string;

    /** Creates a new ChannelActionResult instance. */
    constructor($$source: Partial<ChannelActionResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChannelActionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ChannelActionResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChannelActionResult($$parsedSource as Partial<ChannelActionResult>);
    }
}

export class ChannelInfo {
    "id": string;
    "sessionId": string;
    "path": string;
    "tty": boolean;
    "startedAt": string;

    /** Creates a new ChannelInfo instance. */
    constructor($$source: Partial<ChannelInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("tty" in $$source)) {
            this["tty"] = false;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChannelInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ChannelInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChannelInfo($$parsedSource as Partial<ChannelInfo>);
    }
}

export class ChannelResult {
    "success": boolean;
    "channelId": string;
    "error": string;

    /** Creates a new ChannelResult instance. */
    constructor($$source: Partial<ChannelResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("channelId" in $$source)) {
            this["channelId"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChannelResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ChannelResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChannelResult($$parsedSource as Partial<ChannelResult>);
    }
}

export class ChannelSpec {
    "sessionId": string;
    "path": string;
    "subprotocols": string[];
    "headers": { [_ in string]?: string };
    "tty": boolean;
    "cols": number;
    "rows": number;

    /** Creates a new ChannelSpec instance. */
    constructor($$source: Partial<ChannelSpec> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("subprotocols" in $$source)) {
            this["subprotocols"] = [];
        }
        if (!("headers" in $$source)) {
            this["headers"] = {};
        }
        if (!("tty" in $$source)) {
            this["tty"] = false;
        }
        if (!("cols" in $$source)) {
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChannelSpec instance from a string or object.
     */
    static createFrom($$source: any = {}): ChannelSpec {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("subprotocols" in $$parsedSource) {
            $$parsedSource["subprotocols"] = $$createField2_0($$parsedSource["subprotocols"]);
        }
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField3_0($$parsedSource["headers"]);
        }
        return new ChannelSpec($$parsedSource as Partial<ChannelSpec>);
    }
}

export class ChannelsResult {
    "success": boolean;
    "channels": ChannelInfo[];
    "error": string;

    /** Creates a new ChannelsResult instance. */
    constructor($$source: Partial<ChannelsResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("channels" in $$source)) {
            this["channels"] = [];
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChannelsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ChannelsResult {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("channels" in $$parsedSource) {
            $$parsedSource["channels"] = $$createField1_0($$parsedSource["channels"]);
        }
        return new ChannelsResult($$parsedSource as Partial<ChannelsResult>);
    }
}

export class ForwardInfo {
    "id": string;
    "sessionId": string;
    "localAddress": string;
    "localPort": number;
    "remotePort": number;
    "connections": number;

    /** Creates a new ForwardInfo instance. */
    constructor($$source: Partial<ForwardInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("localAddress" in $$source)) {
            this["localAddress"] = "";
        }
        if (!("localPort" in $$source)) {
            this["localPort"] = 0;
        }
        if (!("remotePort" in $$source)) {
            this["remotePort"] = 0;
        }
        if (!("connections" in $$source)) {
            this["connections"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForwardInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ForwardInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ForwardInfo($$parsedSource as Partial<ForwardInfo>);
    }
}

export class ForwardsResult {
    "success": boolean;
    "forwards": ForwardInfo[];
    "error": string;

    /** Creates a new ForwardsResult instance. */
    constructor($$source: Partial<ForwardsResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("forwards" in $$source)) {
            this["forwards"] = [];
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForwardsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ForwardsResult {
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("forwards" in $$parsedSource) {
            $$parsedSource["forwards"] = $$createField1_0($$parsedSource["forwards"]);
        }
        return new ForwardsResult($$parsedSource as Partial<ForwardsResult>);
    }
}

export class PortForwardResult {
    "success": boolean;
    "forwardId": string;
    "localPort": number;
    "error": string;

    /** Creates a new PortForwardResult instance. */
    constructor($$source: Partial<PortForwardResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("forwardId" in $$source)) {
            this["forwardId"] = "";
        }
        if (!("localPort" in $$source)) {
            this["localPort"] = 0;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortForwardResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PortForwardResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortForwardResult($$parsedSource as Partial<PortForwardResult>);
    }
}

export class PortForwardSpec {
    "sessionId": string;
    "path": string;
    "subprotocols": string[];
    "headers": { [_ in string]?: string };
    "localPort": number;
    "localAddress": string;
    "remotePort": number;

    /** Creates a new PortForwardSpec instance. */
    constructor($$source: Partial<PortForwardSpec> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("subprotocols" in $$source)) {
            this["subprotocols"] = [];
        }
        if (!("headers" in $$source)) {
            this["headers"] = {};
        }
        if (!("localPort" in $$source)) {
            this["localPort"] = 0;
        }
        if (!("localAddress" in $$source)) {
            this["localAddress"] = "";
        }
        if (!("remotePort" in $$source)) {
            this["remotePort"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortForwardSpec instance from a string or object.
     */
    static createFrom($$source: any = {}): PortForwardSpec {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("subprotocols" in $$parsedSource) {
            $$parsedSource["subprotocols"] = $$createField2_0($$parsedSource["subprotocols"]);
        }
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField3_0($$parsedSource["headers"]);
        }
        return new PortForwardSpec($$parsedSource as Partial<PortForwardSpec>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = ChannelInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = ForwardInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
