export { ServiceEntity } from '@/domain/entities/network/ServiceEntity'
export { IngressEntity } from '@/domain/entities/network/IngressEntity'
export { ServiceTypeCatalog } from '@/domain/entities/network/ServiceTypeCatalog'
export type { TIngressRule } from '@/domain/entities/network/types/TIngressRule'
export type { TIngressSpec } from '@/domain/entities/network/types/TIngressSpec'
export type { TIngressTls } from '@/domain/entities/network/types/TIngressTls'
export type { TLoadBalancerIngress } from '@/domain/entities/network/types/TLoadBalancerIngress'
export type { TLoadBalancerStatus } from '@/domain/entities/network/types/TLoadBalancerStatus'
export type { TServicePort } from '@/domain/entities/network/types/TServicePort'
export type { TServiceSpec } from '@/domain/entities/network/types/TServiceSpec'
export type { TServiceType } from '@/domain/entities/network/types/TServiceType'
