// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Connect(spec: $models.ConnectionSpec): $CancellablePromise<$models.ConnectResult> {
    return $Call.ByID(1663953386, spec).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Disconnect(id: string): $CancellablePromise<$models.KubeResult> {
    return $Call.ByID(1237828558, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Sessions(): $CancellablePromise<$models.SessionsResult> {
    return $Call.ByID(2828360089).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ConnectResult.createFrom;
const $$createType1 = $models.KubeResult.createFrom;
const $$createType2 = $models.SessionsResult.createFrom;
