// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Send(request: $models.Request): $CancellablePromise<$models.Response> {
    return $Call.ByID(1119235391, request).then(($result: any) => {
        return $$createType0($result);
    });
}

export function StartStream(request: $models.StreamRequest): $CancellablePromise<$models.StreamResult> {
    return $Call.ByID(1801196527, request).then(($result: any) => {
        return $$createType1($result);
    });
}

export function StopStream(streamId: string): $CancellablePromise<$models.KubeResult> {
    return $Call.ByID(2537538389, streamId).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Streams(): $CancellablePromise<$models.StreamsResult> {
    return $Call.ByID(2428322418).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Response.createFrom;
const $$createType1 = $models.StreamResult.createFrom;
const $$createType2 = $models.KubeResult.createFrom;
const $$createType3 = $models.StreamsResult.createFrom;
