// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ConnectResult {
    "success": boolean;
    "sessionId": string;
    "error": string;

    /** Creates a new ConnectResult instance. */
    constructor($$source: Partial<ConnectResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectResult($$parsedSource as Partial<ConnectResult>);
    }
}

export class ConnectionSpec {
    "server": string;
    "caPem": string;
    "clientCertPem": string;
    "clientKeyPem": string;
    "token": string;
    "username": string;
    "password": string;
    "insecureSkipTlsVerify": boolean;
    "serverName": string;
    "proxyUrl": string;
    "timeoutSeconds": number;

    /** Creates a new ConnectionSpec instance. */
    constructor($$source: Partial<ConnectionSpec> = {}) {
        if (!("server" in $$source)) {
            this["server"] = "";
        }
        if (!("caPem" in $$source)) {
            this["caPem"] = "";
        }
        if (!("clientCertPem" in $$source)) {
            this["clientCertPem"] = "";
        }
        if (!("clientKeyPem" in $$source)) {
            this["clientKeyPem"] = "";
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("insecureSkipTlsVerify" in $$source)) {
            this["insecureSkipTlsVerify"] = false;
        }
        if (!("serverName" in $$source)) {
            this["serverName"] = "";
        }
        if (!("proxyUrl" in $$source)) {
            this["proxyUrl"] = "";
        }
        if (!("timeoutSeconds" in $$source)) {
            this["timeoutSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionSpec instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionSpec {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionSpec($$parsedSource as Partial<ConnectionSpec>);
    }
}

export class KubeResult {
    "success": boolean;
    "error": string;

    /** Creates a new KubeResult instance. */
    constructor($$source: Partial<KubeResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KubeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): KubeResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KubeResult($$parsedSource as Partial<KubeResult>);
    }
}

export class Request {
    "sessionId": string;
    "method": string;
    "path": string;
    "headers": { [_ in string]?: string };
    "body": string;
    "timeoutSeconds": number;

    /** Creates a new Request instance. */
    constructor($$source: Partial<Request> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("headers" in $$source)) {
            this["headers"] = {};
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("timeoutSeconds" in $$source)) {
            this["timeoutSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Request instance from a string or object.
     */
    static createFrom($$source: any = {}): Request {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField3_0($$parsedSource["headers"]);
        }
        return new Request($$parsedSource as Partial<Request>);
    }
}

export class Response {
    "success": boolean;
    "status": number;
    "headers": { [_ in string]?: string };
    "body": string;
    "error": string;

    /** Creates a new Response instance. */
    constructor($$source: Partial<Response> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("headers" in $$source)) {
            this["headers"] = {};
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Response instance from a string or object.
     */
    static createFrom($$source: any = {}): Response {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField2_0($$parsedSource["headers"]);
        }
        return new Response($$parsedSource as Partial<Response>);
    }
}

export class SessionInfo {
    "id": string;
    "server": string;
    "createdAt": string;

    /** Creates a new SessionInfo instance. */
    constructor($$source: Partial<SessionInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("server" in $$source)) {
            this["server"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionInfo($$parsedSource as Partial<SessionInfo>);
    }
}

export class SessionsResult {
    "success": boolean;
    "sessions": SessionInfo[];
    "error": string;

    /** Creates a new SessionsResult instance. */
    constructor($$source: Partial<SessionsResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("sessions" in $$source)) {
            this["sessions"] = [];
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionsResult {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sessions" in $$parsedSource) {
            $$parsedSource["sessions"] = $$createField1_0($$parsedSource["sessions"]);
        }
        return new SessionsResult($$parsedSource as Partial<SessionsResult>);
    }
}

export class StreamInfo {
    "id": string;
    "sessionId": string;
    "path": string;
    "mode": string;
    "startedAt": string;

    /** Creates a new StreamInfo instance. */
    constructor($$source: Partial<StreamInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamInfo($$parsedSource as Partial<StreamInfo>);
    }
}

export class StreamRequest {
    "sessionId": string;
    "method": string;
    "path": string;
    "headers": { [_ in string]?: string };
    "body": string;
    "mode": string;

    /** Creates a new StreamRequest instance. */
    constructor($$source: Partial<StreamRequest> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("headers" in $$source)) {
            this["headers"] = {};
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamRequest {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField3_0($$parsedSource["headers"]);
        }
        return new StreamRequest($$parsedSource as Partial<StreamRequest>);
    }
}

export class StreamResult {
    "success": boolean;
    "streamId": string;
    "error": string;

    /** Creates a new StreamResult instance. */
    constructor($$source: Partial<StreamResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("streamId" in $$source)) {
            this["streamId"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamResult instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamResult($$parsedSource as Partial<StreamResult>);
    }
}

export class StreamsResult {
    "success": boolean;
    "streams": StreamInfo[];
    "error": string;

    /** Creates a new StreamsResult instance. */
    constructor($$source: Partial<StreamsResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("streams" in $$source)) {
            this["streams"] = [];
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamsResult {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("streams" in $$parsedSource) {
            $$parsedSource["streams"] = $$createField1_0($$parsedSource["streams"]);
        }
        return new StreamsResult($$parsedSource as Partial<StreamsResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = SessionInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = StreamInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
