// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as JournalService from "./journalservice.js";
export {
    JournalService
};

export {
    Entry,
    JournalResult
} from "./models.js";
