// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Entry {
    "level": string;
    "component": string;
    "event": string;
    "method": string;
    "path": string;
    "status": number;
    "session": string;
    "duration": number;
    "message": string;
    "trace": string;

    /** Creates a new Entry instance. */
    constructor($$source: Partial<Entry> = {}) {
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("component" in $$source)) {
            this["component"] = "";
        }
        if (!("event" in $$source)) {
            this["event"] = "";
        }
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("session" in $$source)) {
            this["session"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("trace" in $$source)) {
            this["trace"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     */
    static createFrom($$source: any = {}): Entry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Entry($$parsedSource as Partial<Entry>);
    }
}

export class JournalResult {
    "success": boolean;
    "error": string;

    /** Creates a new JournalResult instance. */
    constructor($$source: Partial<JournalResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JournalResult instance from a string or object.
     */
    static createFrom($$source: any = {}): JournalResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JournalResult($$parsedSource as Partial<JournalResult>);
    }
}
