// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class StorageInfo {
    "success": boolean;
    "root": string;
    "logs": string;
    "version": number;
    "error": string;

    /** Creates a new StorageInfo instance. */
    constructor($$source: Partial<StorageInfo> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("logs" in $$source)) {
            this["logs"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StorageInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): StorageInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StorageInfo($$parsedSource as Partial<StorageInfo>);
    }
}
